-- MySQL Script generated by MySQL Workbench
-- Thu May 27 13:15:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Web-Motion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Web-Motion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Web-Motion` DEFAULT CHARACTER SET utf8 ;
USE `Web-Motion` ;

-- -----------------------------------------------------
-- Table `Web-Motion`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Web-Motion`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `name/surname` VARCHAR(45) NULL,
  `phone_num` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `question` VARCHAR(500) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
